version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    ports:
      - '5432:5432'
    networks:
      - local
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
networks:
  local:
volumes:
  timescaledb_data:
  mongo_data:
  cache_data:
    driver: local
